Preparing training and test sets...
Creating samples using as look_back = 5
There are 284947 sequences with  58561 users.
Current iteration: 0
Current number of epochs: 10
Current number of look_backs: 5
WARNING:tensorflow:From /Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 6, 50)             11000     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
=================================================================
Total params: 31,251
Trainable params: 31,251
Non-trainable params: 0
_________________________________________________________________
Training...
2019-10-10 15:54:45.442615: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Epoch 1/10
 - 10s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4264e-04 - recall_m: 0.0219
Epoch 2/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4264e-04 - recall_m: 0.0236
Epoch 3/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4273e-04 - recall_m: 0.0236
Epoch 4/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4128e-04 - recall_m: 0.0232
Epoch 5/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4477e-04 - recall_m: 0.0236
Epoch 6/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4482e-04 - recall_m: 0.0236
Epoch 7/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4400e-04 - recall_m: 0.0236
Epoch 8/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4332e-04 - recall_m: 0.0232
Epoch 9/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4608e-04 - recall_m: 0.0232
Epoch 10/10
 - 9s - loss: 0.7264 - acc: 0.0094 - f1_m: 0.0014 - precision_m: 7.4337e-04 - recall_m: 0.0236
Training done. Duration (s) : %s 91.76546001434326
Training Loss per epoch: [0.7263861788480854, 0.7263861794956892, 0.7263861786171569, 0.7263861791241956, 0.7263861788832267, 0.7263861786372376, 0.7263861801031314, 0.7263861800077479, 0.7263861790990946, 0.7263861801734139]
dict_keys(['loss', 'acc', 'f1_m', 'precision_m', 'recall_m'])
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 122, in <module>
    results.append(experiment(bonifici, repeats, e, l))
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 108, in experiment
    loss, accuracy, f1_score, precision, recall = history.evaluate(x_test, y_test, verbose=0)
AttributeError: 'History' object has no attribute 'evaluate'
PyDev console: starting.

Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
