Feature engineering
Preparing training and test sets
Ci sono 6 serie con 257 utenti.
Ci sono 0 serie con 56 utenti.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 20, 4)             144       
_________________________________________________________________
dropout_1 (Dropout)          (None, 20, 4)             0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 16)                1344      
_________________________________________________________________
dropout_2 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 68        
=================================================================
Total params: 1,556
Trainable params: 1,556
Non-trainable params: 0
_________________________________________________________________
Training model...
Training
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/main_LSTM.py", line 124, in <module>
    history = LSTM.train_model(model, x_train, y_train, batch_size, epochs, shuffle, validation, ([], []), patience)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/models/LSTM.py", line 61, in train_model
    history_callback = model.fit(x_train, y_train, epochs=epochs, verbose=2, callbacks=[WandbCallback()])
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected lstm_1_input to have shape (20, 4) but got array with shape (50, 4)
PyDev console: starting.

Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
